CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(200) CHECK (email = '%@%'),
    login varchar(200) NOT NULL,
    name varchar(200),
    birthday DATE CHECK (birthday < CURRENT_DATE),
    CONSTRAINT login_no_spaces CHECK (login != '% %')
);

CREATE TABLE IF NOT EXISTS friend_ids (
    user_id INTEGER REFERENCES users(id),
    friend_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS rating (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(5)
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    description varchar(200),
    release_date DATE CHECK release_date > CAST('1895-12-28' AS DATE),
    duration INTEGER CHECK duration > 0,
    rating_id INTEGER REFERENCES rating(id)
);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id INTEGER REFERENCES films(id),
    user_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(5)
);

CREATE TABLE IF NOT EXISTS genre_likes (
    film_id INTEGER REFERENCES films(id),
    genre_id INTEGER REFERENCES genre(id)
);