CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(200),
    login varchar(200),
    name varchar(200),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS friend_ids (
    user_id INTEGER REFERENCES users(id),
    friend_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS rating (
    id INTEGER PRIMARY KEY,
    name varchar(5)
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200),
    description varchar(200),
    release_date DATE,
    duration INTEGER,
    rating_id INTEGER REFERENCES rating(id)
);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id INTEGER REFERENCES films(id),
    user_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS genre (
    id INTEGER PRIMARY KEY,
    name varchar(50)
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id INTEGER REFERENCES films(id),
    genre_id INTEGER REFERENCES genre(id)
);